In [1]:
import numpy as np

# [Problem 1] Matrix product is calculated manually

In [ ]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

Given two matrices $A(m,k)$ and $B(k,n)$. Their dot product $<.>$ is defined as a matrix $C$ with size $(m,n)$. Each entry of matrix $C$ for row $a$ ($a \in [1,m]$) and column $b$ ($b \in [1,n]$) is the sum of products of entries from row $a$ of matrix $A$ and column $b$ of matrix $B$. In other word: $C[i][j] = \sum_{k}{A[i][k]*B[k][j]}$.

The answer for this question is:
\begin{bmatrix}
6 & 29 & -20\\
12 & 52 & 38\\
-18 & -51 & -48
\end{bmatrix}
Example calculation: \\
$C[1][1] = 6 = (-1).0 + 2.0 + 3.2$

# [Problem 2] Calculation by NumPy function

In [19]:
print(np.matmul(a_ndarray, b_ndarray))
print(np.dot(a_ndarray, b_ndarray))
print(a_ndarray @ b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# [Problem 3] Implementation of calculation of a certain element

In [31]:
def dot_product_simple(a, b, row_a=0, column_b=0):
    sum = 0
    for x, y in zip(a[row_a,:], b[:,column_b]):
        sum += x*y
    return sum
print(dot_product_simple(a_ndarray,b_ndarray))

6


# [Problem 4] Creating a function that performs matrix multiplication

In [32]:
def dot_product(a, b):
    c = np.zeros((a.shape[0], b.shape[1]))
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            c[i][j] = dot_product_simple(a, b, i, j)
    return c
print(dot_product(a_ndarray,b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# [Problem 5] Judge the input whose calculation is not defined

In [35]:
def dot_product_complex(a,b):
    if a.shape[1] == b.shape[0]:
        return dot_product(a,b)
    else:
        print("Conflict matrices' sizes!")
        return np.nan

In [38]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
print(dot_product_complex(d_ndarray, e_ndarray))

Conflict matrices' sizes!
nan


# [Problem 6] Transposition

In [39]:
print(dot_product_complex(d_ndarray, e_ndarray.T))

[[ 46.  -4.]
 [-34.  73.]]
