In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
import pandas as pd 
import numpy as np
import warnings

In [2]:
data = load_iris()
x = data.data[:10]
display(pd.DataFrame(x))
scaler = StandardScaler()
scaler.fit(x)
print("Mean :", scaler.mean_)
print("Var  :", scaler.var_)
x_std = scaler.transform(x)
display(pd.DataFrame(x_std).index)

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2
5  5.4  3.9  1.7  0.4
6  4.6  3.4  1.4  0.3
7  5.0  3.4  1.5  0.2
8  4.4  2.9  1.4  0.2
9  4.9  3.1  1.5  0.1

Mean : [4.86 3.31 1.45 0.22]
Var  : [0.0764 0.0849 0.0105 0.0056]


RangeIndex(start=0, stop=10, step=1)

In [3]:
pd.DataFrame(x_std)

0         1        2         3
0  0.868290  0.652078 -0.48795 -0.267261
1  0.144715 -1.063917 -0.48795 -0.267261
2 -0.578860 -0.377519 -1.46385 -0.267261
3 -0.940647 -0.720718  0.48795 -0.267261
4  0.506502  0.995277 -0.48795 -0.267261
5  1.953651  2.024875  2.43975  2.405351
6 -0.940647  0.308879 -0.48795  1.069045
7  0.506502  0.308879  0.48795 -0.267261
8 -1.664222 -1.407116 -0.48795 -0.267261
9  0.144715 -0.720718  0.48795 -1.603567

# [Problem 1] Enumeration of classes used so far

- pandas:
> DataFrame  
> Series
- matplotlib:
> figure  
> patches
- sklearn:
> datasets  
> preprosessing

# [Problem 2] Enumeration of methods and instance variables used so far

- pandas.DataFrame():  
  
> Instance variable:
>> [dtypes](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dtypes.html)  
>> [columns](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.columns.html)  
>> [shape](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.shape.html)  
>> [loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html)  
>> [iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html)

> Method:
>> [count()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.count.html)  
>> [describe()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html)  
>> [info()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html)  
>> [dropna()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html)  
>> [head()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.head.html)  

# [Problem 3] Creating a standardized class by scratch

In [4]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)
        pass
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        pass
        return X_scaled

In [5]:
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


# [Problem 4] Creating a class that performs 4 arithmetic operations

In [36]:
class ExampleClass():
    def __init__(self, value):
        if isinstance(value, (int, float, complex)):
            self.value = value
        else :
            warnings.warn("Value is a numeric value")
            self.value = 0
    def __add__(self, value2):
        self.value += value2
        return self
    def __sub__(self, value2):
        self.value -= value2
        return self
    def __mul__(self, value2):
        self.value *= value2
        return self
    def __div__(self, value2):
        if value2 == 0:
            warnings.warn("Division by 0")
        else :
            self.value /= value2
            return self
    def add(self, value2):
        return self + value2
    def __str__(self):
        return str(self.value)

In [37]:
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

value : 5
value : 8
